apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordinatest
spec:
  selector:
    matchLabels:
      app: wordpress
  replicas: 2
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpresss
        ports:
        - containerPort: 8080