apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: argoordina-testapp
  name: argoordina-service
  namespace: argoordina
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: myapp